version: 2

builds:
  - main: .
    binary: shiplog
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: HabibPro1999
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: shiplog
    homepage: "https://github.com/HabibPro1999/shiplog"
    description: "Export Claude Code sessions to beautiful, shareable HTML chat logs"
    license: "MIT"
    install: |
      bin.install "shiplog"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
