version: 2

builds:
  - main: .
    binary: shiplog
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: HabibPro1999
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: shiplog
    binaries:
      - shiplog
    homepage: "https://github.com/HabibPro1999/shiplog"
    description: "Export Claude Code sessions to beautiful, shareable HTML chat logs"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
